title: "Generative AI in Academic Research: Database on Usage, Perce"
description: "Structured database on the use of generative artificial intelligence (GAI) in academic research and university teaching in Latin America (2022-2025). "
author: "Juan Moisés de la Serna Tuya"
url: "https://juanmoisesd.github.io"
baseurl: "/generative-ai-in-academic-research-database-on-usage-perception-and-productivity"
